export const products = [
  {
    id: '1',
    name: 'Plaquettes de frein avant',
    brand: 'Toyota Genuine',
    vehicle: 'Toyota Corolla 2014-2019',
    price: 45000,
    oldPrice: 55000,
    quality: 'OEM',
    seller: 'BigMoteurs',
    sellerBadge: 'Premium' as const,
    rating: 4.9,
    reviews: 127,
    delivery: 'RAPID PIECES',
    deliveryTime: '< 1h',
    inStock: true,
    category: 'Freinage',
    image: '/products/plaquettes_de_frein_avant.jpg',
  },
  {
    id: '2',
    name: 'Filtre à huile moteur',
    brand: 'Toyota Genuine',
    vehicle: 'Toyota Corolla 2014-2019',
    price: 12500,
    oldPrice: 15000,
    quality: 'Genuine',
    seller: 'Sotra Pièces',
    sellerBadge: 'Verified' as const,
    rating: 4.7,
    reviews: 89,
    delivery: 'RAPID CITY',
    deliveryTime: '< 2h',
    inStock: true,
    category: 'Filtration',
    image: '/products/filtre_a_huile_moteur.webp',
  },
  {
    id: '3',
    name: 'Alternateur reconditionné',
    brand: 'Denso',
    vehicle: 'Toyota Corolla 2015',
    price: 85000,
    quality: 'Reconditionné',
    seller: 'Diallo & Frères',
    sellerBadge: 'Verified' as const,
    rating: 4.8,
    reviews: 56,
    delivery: 'RAPID CITY',
    deliveryTime: '< 2h',
    inStock: true,
    category: 'Moteur',
    image: '/products/alternateur_reconditionne.webp',
  },
  {
    id: '4',
    name: 'Amortisseur arrière gauche',
    brand: 'Bilstein',
    vehicle: 'Honda Civic 2016-2021',
    price: 72000,
    oldPrice: 85000,
    quality: 'Premium',
    seller: 'Massa Garage',
    sellerBadge: 'Verified' as const,
    rating: 4.6,
    reviews: 34,
    delivery: 'RAPID CITY',
    deliveryTime: '< 2h',
    inStock: true,
    category: 'Suspension',
    image: '/products/Amortisseur_arriere_gauche.webp',
  },
  {
    id: '5',
    name: 'Kit d\'embrayage complet',
    brand: 'Sachs',
    vehicle: 'Toyota Hilux 2015-2020',
    price: 185000,
    oldPrice: 220000,
    quality: 'OEM',
    seller: 'BigMoteurs',
    sellerBadge: 'Premium' as const,
    rating: 4.9,
    reviews: 78,
    delivery: 'RAPID NIGERIA',
    deliveryTime: '48h',
    inStock: false,
    category: 'Transmission',
    image: '/products/Kit_embrayage_complet.jpg',
  },
  {
    id: '6',
    name: 'Batterie 60Ah',
    brand: 'Bosch',
    vehicle: 'Universel',
    price: 65000,
    quality: 'Standard',
    seller: 'Sotra Pièces',
    sellerBadge: 'Verified' as const,
    rating: 4.5,
    reviews: 203,
    delivery: 'RAPID PIECES',
    deliveryTime: '< 1h',
    inStock: true,
    category: 'Électronique',
    image: '/products/batterie.webp',
  },
  {
    id: '7',
    name: 'Pneu 205/55R16',
    brand: 'Michelin',
    vehicle: 'Universel',
    price: 55000,
    oldPrice: 65000,
    quality: 'Premium',
    seller: 'Diallo & Frères',
    sellerBadge: 'Verified' as const,
    rating: 4.8,
    reviews: 156,
    delivery: 'RAPID PIECES',
    deliveryTime: '< 1h',
    inStock: true,
    category: 'Suspension',
    image: '/products/pneu.webp',
  },
  {
    id: '8',
    name: 'Bobine d\'allumage',
    brand: 'NGK',
    vehicle: 'Honda Civic 2016-2021',
    price: 35000,
    quality: 'Aftermarket',
    seller: 'Massa Garage',
    sellerBadge: 'Verified' as const,
    rating: 4.4,
    reviews: 42,
    delivery: 'RAPID CITY',
    deliveryTime: '< 2h',
    inStock: true,
    category: 'Électronique',
    image: '/products/bobine.jpg',
  },
  {
    id: '9',
    name: 'Phare avant droit',
    brand: 'Toyota Genuine',
    vehicle: 'Toyota RAV4 2015-2018',
    price: 120000,
    oldPrice: 145000,
    quality: 'OEM',
    seller: 'BigMoteurs',
    sellerBadge: 'Premium' as const,
    rating: 4.9,
    reviews: 67,
    delivery: 'RAPID USA',
    deliveryTime: '7 jours',
    inStock: false,
    category: 'Éclairage',
    image: '/products/phare_avant_droit.jpg',
  },
  {
    id: '10',
    name: 'Radiateur moteur',
    brand: 'Denso',
    vehicle: 'Honda Civic 2016-2021',
    price: 95000,
    quality: 'Genuine',
    seller: 'Sotra Pièces',
    sellerBadge: 'Verified' as const,
    rating: 4.7,
    reviews: 28,
    delivery: 'RAPID CITY',
    deliveryTime: '< 2h',
    inStock: true,
    category: 'Moteur',
    image: '/products/radiateur_moteur.jpg',
  },
  {
    id: '11',
    name: 'Disque de frein avant',
    brand: 'Brembo',
    vehicle: 'Toyota Corolla 2014-2019',
    price: 38000,
    quality: 'Premium',
    seller: 'Diallo & Frères',
    sellerBadge: 'Verified' as const,
    rating: 4.8,
    reviews: 91,
    delivery: 'RAPID PIECES',
    deliveryTime: '< 1h',
    inStock: true,
    category: 'Freinage',
    image: '/products/disque_frein_avant.jpg',
  },
  {
    id: '12',
    name: 'Courroie accessoires',
    brand: 'Gates',
    vehicle: 'Toyota Corolla 2014-2019',
    price: 28000,
    quality: 'Premium',
    seller: 'Massa Garage',
    sellerBadge: 'Verified' as const,
    rating: 4.6,
    reviews: 45,
    delivery: 'RAPID CITY',
    deliveryTime: '< 2h',
    inStock: true,
    category: 'Moteur',
    image: '/products/courroie_accessoires.jpg',
  },
];

export const categories = [
  { name: 'Freinage', count: 145 },
  { name: 'Moteur', count: 230 },
  { name: 'Éclairage', count: 89 },
  { name: 'Climatisation', count: 67 },
  { name: 'Filtration', count: 134 },
  { name: 'Suspension', count: 112 },
  { name: 'Carrosserie', count: 178 },
  { name: 'Électronique', count: 95 },
  { name: 'Transmission', count: 88 },
  { name: 'Direction', count: 56 },
];

export const deliveryOptions = [
  { label: 'RAPID PIECES', desc: 'Vendeur local', time: '< 1h' },
  { label: 'RAPID CITY', desc: 'Intra-ville', time: '< 2h' },
  { label: 'RAPID NIGERIA', desc: 'Sourcing Nigeria', time: '48h' },
  { label: 'RAPID USA', desc: 'Sourcing USA', time: '7 jours' },
];
